version: '3'
services:
  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'test'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'pass'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: foo
      MONGO_INITDB_ROOT_PASSWORD: bar
      MONGO_INITDB_DATABASE: admin
    ports:
      - "27017:27017"
    volumes:
     - my-mongo:/data/db
  redis:
    image: redis:alpine
    container_name: redis
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "6379:6379"
    volumes:
      - my-redis:/var/lib/redis
# Names our volume
volumes:
  my-db:
  my-mongo:
  my-redis:
